name: Viam cloud build
description: Build and publish your Viam module on multiple platforms.

inputs:
  meta-path:
    description: location of module metadata. set to empty string to not use
    default: meta.json
  key-id:
    description: ID of your auth key
    required: true
  key-value:
    description: secret value of your auth key
    required: true
  version:
    description: Version to set for the module. If missing, your module will build but not upload.
  ref:
    description: The git ref to build. This will usually be a sha, but can be a branch or anything supported by git checkout.
  token:
    description: Pass `github.token` if this is a private repository.

runs:
  using: node20
  main: 'dist/index.js'

branding:
  icon: upload-cloud
