on:
  push:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: npm install
    - name: lint
      run: node_modules/.bin/eslint src
    - name: confirm js artifact matches source
      run: |
        make -B dist/index.js
        git diff --exit-code
