on:
  push:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        meta-path: test/meta.json
        key-id: KEY ID
        key-value: KEY VALUE
